//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueDataWeb.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class AboutCategory
    {
        public int AboutID { get; set; }
        public string Name { get; set; }
        public string Status { get; set; }
        public Nullable<int> Parentcate { get; set; }
        public string Contents { get; set; }
        public string ShortDescription { get; set; }
        public string SmallImage { get; set; }
        public string LargeImage { get; set; }
        public string Note { get; set; }
        public string Type { get; set; }
        public string MetaKeywords { get; set; }
        public string MetaDescription { get; set; }
        public Nullable<int> TinhTrang { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
