//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueDataWeb.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class Album
    {
        public long AlbumID { get; set; }
        public string AlbumName { get; set; }
        public string AlbumDes { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
