//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueDataWeb.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArchitectureCategory
    {
        public ArchitectureCategory()
        {
            this.ArchitectureNews = new HashSet<ArchitectureNew>();
        }
    
        public long ID { get; set; }
        public Nullable<int> AppID { get; set; }
        public string Name { get; set; }
        public Nullable<bool> IsShow { get; set; }
        public string Description { get; set; }
        public Nullable<int> ParentCategoryID { get; set; }
        public string MetaKeywords { get; set; }
        public string MetaDescription { get; set; }
        public string MetaTitle { get; set; }
        public string Class { get; set; }
        public string Image { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public string KeyName { get; set; }
        public string ViewName { get; set; }
        public string DescriptionContent { get; set; }
    
        public virtual ICollection<ArchitectureNew> ArchitectureNews { get; set; }
    }
}
