//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueDataWeb.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaoGia_GiaTri
    {
        public long Id { get; set; }
        public int AppID { get; set; }
        public long LoaiBaoGiaID { get; set; }
        public long BaoGiaID { get; set; }
        public string TenThuocTinh { get; set; }
        public string GiaTriThuocTinh { get; set; }
        public Nullable<bool> IsDefault { get; set; }
        public Nullable<int> OrderBy { get; set; }
    }
}
