//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueDataWeb.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaoGia_Loai
    {
        public long ID { get; set; }
        public string TenLoaiBaoGia { get; set; }
        public string MoTa { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public int AppID { get; set; }
    }
}
