//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueDataWeb.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaoGia
    {
        public long BaoGiaID { get; set; }
        public int AppID { get; set; }
        public int LoaiBaoGiaID { get; set; }
        public string Ten { get; set; }
        public string MoTa { get; set; }
        public string MoTaNgan { get; set; }
        public string MetaTitle { get; set; }
        public string MetaKeyword { get; set; }
        public string MetaDescription { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string HinhAnh { get; set; }
        public string DocumentFile { get; set; }
        public string Video { get; set; }
        public string TongGia { get; set; }
        public Nullable<int> OrderBy { get; set; }
        public Nullable<bool> IsHot { get; set; }
        public string FileBaoGia { get; set; }
    }
}
