//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueDataWeb.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaoGia_Loai_ThuocTinh
    {
        public long ID { get; set; }
        public int AppID { get; set; }
        public long LoaiBaoGiaID { get; set; }
        public string Ten { get; set; }
        public string GiaTri { get; set; }
        public Nullable<bool> AllowDelete { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<int> OrderBy { get; set; }
    }
}
