//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueDataWeb.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public int ContactId { get; set; }
        public Nullable<int> AppID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Fax { get; set; }
        public string contents { get; set; }
        public string Title { get; set; }
        public string DichVu { get; set; }
        public string MoTaDichVu { get; set; }
        public string TypeContact { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string ChucVu { get; set; }
        public string LinhVuc { get; set; }
        public string CongTy { get; set; }
        public Nullable<long> BangGiaID { get; set; }
        public string BangGiaChiTiet { get; set; }
    }
}
