//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueDataWeb.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExportBill
    {
        public int ID { get; set; }
        public string ShipperName { get; set; }
        public string ShipperTel { get; set; }
        public string ShipperCompany { get; set; }
        public string ShipperAddress { get; set; }
        public string RecieverName { get; set; }
        public string RecieverTel { get; set; }
        public string RecieverCompany { get; set; }
        public string RecieverAddress { get; set; }
        public string RecieverContry { get; set; }
        public string RecieverPostCode { get; set; }
        public string Service { get; set; }
        public string DescriptionNo { get; set; }
        public string DescriptionActualWeight { get; set; }
        public string DescriptionDimWeight { get; set; }
        public string DescriptionValue { get; set; }
        public string DescriptionContents { get; set; }
        public string DescriptionExport { get; set; }
        public string ShipperCountry { get; set; }
        public string Countrytemp { get; set; }
        public string RecieverCountry { get; set; }
        public string RecieverCounTryTemp { get; set; }
    }
}
