//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueDataWeb.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public int ImageId { get; set; }
        public Nullable<int> AppID { get; set; }
        public string ImagePath { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<bool> IsSlider { get; set; }
        public string Type { get; set; }
        public Nullable<bool> IsShow { get; set; }
        public string ImgName { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public string Description { get; set; }
        public string ImageTile { get; set; }
        public string ImageThumb { get; set; }
        public Nullable<long> AlbumID { get; set; }
        public string Name { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
