//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueDataWeb.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class LabelProduct
    {
        public LabelProduct()
        {
            this.Products = new HashSet<Product>();
        }
    
        public int Id { get; set; }
        public string Label { get; set; }
        public string Company { get; set; }
    
        public virtual ICollection<Product> Products { get; set; }
    }
}
