//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueDataWeb.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class Price
    {
        public long Id { get; set; }
        public Nullable<int> AppID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<double> PriceChucNang { get; set; }
        public string JSonChucNang { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
