//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueDataWeb.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ward
    {
        public Ward()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int WardID { get; set; }
        public int ID { get; set; }
        public string TenPhuongXa { get; set; }
        public int MaQuanHuyen { get; set; }
        public string XuatBan { get; set; }
        public string ThuTu { get; set; }
    
        public virtual District District { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
    }
}
