//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueDataWeb.Models.CustomsModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductDescription
    {
        public int ProductDescriptionId { get; set; }
        public string ProductCode { get; set; }
        public string Title { get; set; }
        public string Contents { get; set; }
    }
}
